"""
CanMV K230 ball-on-beam vision, three operating modes and UART4 telemetry.

LCD touch modes:
    M1 CENTER : keep the ball at beam center (0 mm).
    M2 SWEEP  : command +50 mm, reverse on arrival, then hold -50 mm.
    M3 TOUCH  : touch any point on the detected beam to choose the target.

UART4:
    GPIO36 -> UART4_TXD
    GPIO37 -> UART4_RXD (initialized, may be left unconnected)
    115200, 8 data bits, no parity, 1 stop bit

The detected beam/track (class 0) defines the physical coordinate system:
its left scale is -120.0 mm, center is 0.0 mm, and right scale is +120.0 mm.

One 12-byte packet is sent for every processed frame. All multi-byte fields
are little-endian:

    Byte 0       : header 0xAA
    Byte 1       : header 0x55
    Byte 2       : frame sequence, uint8
    Byte 3       : flags
                     bit 0: ball position is valid
                     bit 1: setpoint is valid
                     bit 2: track detected in the current frame
                     bit 3: mode 2 sequence is complete
                     bit 4..5: mode number (1, 2 or 3)
                     bit 6: ball detected in the current frame
                     bit 7: edge-loss recovery is active
    Byte 4       : ball confidence, uint8 (0..100 percent)
    Byte 5..6    : ball position, int16 (unit: 0.1 mm)
    Byte 7..8    : ball velocity, int16 (unit: 0.1 mm/s)
    Byte 9..10   : active setpoint, int16 (unit: 0.1 mm)
    Byte 11      : XOR of bytes 0..10
"""

from libs.PipeLine import PipeLine
from libs.YOLO import YOLO11
from libs.Utils import *
from media.sensor import *
from machine import FPIOA, TOUCH, UART
import os, sys, gc, ujson
import ulab.numpy as np
import image
import time


# --------------------------- Model configuration ---------------------------
kmodel_path = "/sdcard/yolo11n_det_320.kmodel"
labels = {0: "slider", 1: "steel ball"}
model_input_size = [320, 320]
# End-zone views partially occlude/crop the ball, so use a lower detector
# threshold and rely on class filtering plus temporal association.
confidence_threshold = 0.25
nms_threshold = 0.45

TRACK_CLASS_ID = 0
BALL_CLASS_ID = 1

# Competition beam scale: -12.0 cm .. +12.0 cm, unit here is 0.1 mm.
POSITION_MIN_X10 = -1200
POSITION_MAX_X10 = 1200

# Three-point visual calibration in normalized track-box coordinates.
# u = (measured_pixel_x - detected_track_left) / detected_track_width
# Replace these defaults after measuring the -120, 0 and +120 mm marks.
CAL_U_NEG120 = 0.0
CAL_U_ZERO = 0.5
CAL_U_POS120 = 1.0
CALIBRATION_FILE = "/sdcard/ball_calibration.json"

# Load the file generated by calibrate-camera.py. Defaults above remain active
# when the file is missing or invalid.
try:
    with open(CALIBRATION_FILE, "r") as calibration_stream:
        calibration_data = ujson.loads(calibration_stream.read())
    loaded_neg120 = float(calibration_data["cal_u_neg120"])
    loaded_zero = float(calibration_data["cal_u_zero"])
    loaded_pos120 = float(calibration_data["cal_u_pos120"])
    if (
        loaded_neg120 < loaded_zero < loaded_pos120
        and loaded_zero - loaded_neg120 > 0.05
        and loaded_pos120 - loaded_zero > 0.05
    ):
        CAL_U_NEG120 = loaded_neg120
        CAL_U_ZERO = loaded_zero
        CAL_U_POS120 = loaded_pos120
        print(
            "Loaded calibration:",
            CAL_U_NEG120,
            CAL_U_ZERO,
            CAL_U_POS120,
        )
    else:
        print("Calibration file rejected: values are not monotonic")
except Exception as calibration_error:
    print("Using default calibration:", calibration_error)

# Track-box filtering reduces position/velocity noise caused by box jitter.
TRACK_FILTER_ALPHA = 0.20
TRACK_HOLD_MS = 3000

# Missing-ball state machine:
#   0 .. BALL_SHORT_PREDICT_MS:
#       bridge ordinary detector flicker using constant-velocity prediction.
#   BALL_EDGE_CONFIRM_MS .. BALL_EDGE_RECOVERY_MS:
#       when the last fresh state was near an end and moving outward, infer
#       that the ball entered the outer zone. Move the estimate from +/-100
#       mm toward +/-120 mm and set FLAG_EDGE_RECOVERY.
#   after BALL_EDGE_RECOVERY_MS:
#       invalidate the position; blind control must not continue indefinitely.
BALL_SHORT_PREDICT_MS = 200
BALL_EDGE_CONFIRM_MS = 80
BALL_EDGE_RECOVERY_MS = 600
BALL_EDGE_ENTRY_X10 = 900               # 90.0 mm / 9.0 cm
BALL_EDGE_ASSUMED_START_X10 = 1000       # 100.0 mm / 10.0 cm
BALL_EDGE_MIN_OUTWARD_SPEED_X10 = 50    # 5.0 mm/s
BALL_POSITION_FILTER_ALPHA = 0.55
BALL_VELOCITY_FILTER_ALPHA = 0.35
BALL_ASSOCIATION_MAX_JUMP_PX = 120

# A finger is much larger than the thin track on the LCD.
TOUCH_Y_MARGIN_PX = 40
UI_BUTTON_HEIGHT_PX = 58

# Operating modes.
MODE_CENTER = 1
MODE_SWEEP = 2
MODE_TOUCH = 3
DEFAULT_MODE = MODE_CENTER

# Mode 2: center -> +50 mm -> -50 mm and hold.
MODE2_POSITIVE_X10 = 500
MODE2_NEGATIVE_X10 = -500
MODE2_TOLERANCE_X10 = 100       # +/-10.0 mm
MODE2_SETTLE_MS = 300           # continuous in-range time at -50 mm
MODE2_TIME_LIMIT_MS = 5000
MODE2_GO_POSITIVE = 0
MODE2_GO_NEGATIVE = 1
MODE2_HOLD_NEGATIVE = 2

# Packet flags.
FLAG_BALL_VALID = 0x01
FLAG_SETPOINT_VALID = 0x02
FLAG_TRACK_FRESH = 0x04
FLAG_MODE2_DONE = 0x08
MODE_FLAG_SHIFT = 4
FLAG_BALL_FRESH = 0x40
FLAG_EDGE_RECOVERY = 0x80

# Set True only while debugging; per-frame printing lowers the frame rate.
DEBUG_PRINT = False


# -------------------------- Display configuration --------------------------
display = "lcd3_5"

if display == "hdmi":
    display_mode = "hdmi"
    display_size = [1920, 1080]
elif display == "lcd3_5":
    display_mode = "st7701"
    display_size = [800, 480]
elif display == "lcd2_4":
    display_mode = "st7701"
    display_size = [640, 480]
else:
    raise ValueError("unsupported display mode: " + display)

rgb888p_size = [640, 360]


def clamp(value, minimum, maximum):
    if value < minimum:
        return minimum
    if value > maximum:
        return maximum
    return value


def predict_missing_ball_state(
    last_position_x10,
    last_velocity_x10,
    last_confidence_percent,
    missing_age_ms,
):
    """
    Estimate a briefly missing ball.

    Returns:
        (valid, position_x10, velocity_x10, confidence, edge_side)
    edge_side is -1 for left recovery, +1 for right recovery and 0 for an
    ordinary short prediction.
    """
    left_edge_candidate = (
        last_position_x10 <= -BALL_EDGE_ENTRY_X10
        and last_velocity_x10 <= -BALL_EDGE_MIN_OUTWARD_SPEED_X10
    )
    right_edge_candidate = (
        last_position_x10 >= BALL_EDGE_ENTRY_X10
        and last_velocity_x10 >= BALL_EDGE_MIN_OUTWARD_SPEED_X10
    )
    edge_candidate = left_edge_candidate or right_edge_candidate

    short_prediction = (
        missing_age_ms >= 0
        and missing_age_ms <= BALL_SHORT_PREDICT_MS
    )
    edge_recovery = (
        edge_candidate
        and missing_age_ms > BALL_EDGE_CONFIRM_MS
        and missing_age_ms <= BALL_EDGE_RECOVERY_MS
    )
    if not short_prediction and not edge_recovery:
        return False, 0, 0, 0, 0

    prediction_limit_ms = (
        BALL_EDGE_RECOVERY_MS
        if edge_candidate
        else BALL_SHORT_PREDICT_MS
    )
    hold_ratio = clamp(
        1.0
        - float(missing_age_ms) / float(prediction_limit_ms),
        0.0,
        1.0,
    )
    predicted_position_x10 = (
        last_position_x10
        + last_velocity_x10 * missing_age_ms / 1000.0
    )
    edge_side = 0

    if edge_recovery:
        # The competition touch targets are normally inside +/-100 mm.
        # Once end loss is confirmed, infer that the ball entered the outer
        # zone and move the estimate gradually toward the physical end.
        recovery_ratio = clamp(
            float(missing_age_ms - BALL_EDGE_CONFIRM_MS)
            / float(BALL_EDGE_RECOVERY_MS - BALL_EDGE_CONFIRM_MS),
            0.0,
            1.0,
        )
        if left_edge_candidate:
            edge_side = -1
            recovery_start_x10 = -BALL_EDGE_ASSUMED_START_X10
            edge_position_x10 = POSITION_MIN_X10
        else:
            edge_side = 1
            recovery_start_x10 = BALL_EDGE_ASSUMED_START_X10
            edge_position_x10 = POSITION_MAX_X10
        predicted_position_x10 = (
            recovery_start_x10
            + recovery_ratio
            * (edge_position_x10 - recovery_start_x10)
        )

    position_x10 = int(round(clamp(
        predicted_position_x10,
        POSITION_MIN_X10,
        POSITION_MAX_X10,
    )))
    velocity_x10 = int(round(last_velocity_x10 * hold_ratio))
    confidence_percent = int(round(
        last_confidence_percent * hold_ratio
    ))
    return (
        True,
        position_x10,
        velocity_x10,
        confidence_percent,
        edge_side,
    )


def put_u16_le(buf, offset, value):
    """Write an unsigned 16-bit integer in little-endian order."""
    value = int(value) & 0xFFFF
    buf[offset] = value & 0xFF
    buf[offset + 1] = (value >> 8) & 0xFF


def put_i16_le(buf, offset, value):
    """Write a signed 16-bit integer in little-endian two's complement."""
    put_u16_le(buf, offset, int(value))


def build_packet(
    sequence,
    flags,
    confidence_percent,
    position_x10,
    velocity_x10,
    setpoint_x10,
):
    """Build the fixed-length 12-byte UART packet."""
    packet = bytearray(12)
    packet[0] = 0xAA
    packet[1] = 0x55
    packet[2] = int(sequence) & 0xFF
    packet[3] = int(flags) & 0xFF
    packet[4] = int(clamp(confidence_percent, 0, 100))
    put_i16_le(packet, 5, clamp(position_x10, -32768, 32767))
    put_i16_le(packet, 7, clamp(velocity_x10, -32768, 32767))
    put_i16_le(packet, 9, clamp(setpoint_x10, -32768, 32767))

    checksum = 0
    for i in range(11):
        checksum ^= packet[i]
    packet[11] = checksum
    return packet


def select_class(
    detections,
    wanted_class_id,
    reference_center_x=None,
    max_jump_px=None,
):
    """
    Return one detection of a class. Without a reference it selects the
    highest confidence; with a reference it selects the nearest candidate.

    CanMV YOLO detect result format:
        detections[0] = boxes [[x, y, width, height], ...]
        detections[1] = class IDs
        detections[2] = confidence scores

    Video-mode box coordinates use the display coordinate system.
    Returns ((x, y, width, height), score), or None.
    """
    if detections is None or len(detections) < 3:
        return None

    boxes = detections[0]
    class_ids = detections[1]
    scores = detections[2]
    if boxes is None or len(boxes) == 0:
        return None

    best_index = -1
    best_score = -1.0
    best_rank = -1000000.0
    for i in range(len(boxes)):
        class_id = int(class_ids[i])
        score = float(scores[i])
        if class_id != wanted_class_id:
            continue

        if reference_center_x is None:
            rank = score
        else:
            box = boxes[i]
            center_x = float(box[0]) + float(box[2]) * 0.5
            distance = abs(center_x - reference_center_x)
            if max_jump_px is not None and distance > max_jump_px:
                continue
            # Temporal proximity is more reliable than confidence after the
            # detector threshold is lowered for partially visible end zones.
            rank = -distance

        if rank > best_rank:
            best_index = i
            best_score = score
            best_rank = rank

    if best_index < 0:
        return None

    box = boxes[best_index]
    stable_box = (
        float(box[0]),
        float(box[1]),
        float(box[2]),
        float(box[3]),
    )
    return stable_box, best_score


def filter_track_box(previous_box, detected_box):
    """Low-pass filter the track box to reduce detection jitter."""
    if previous_box is None:
        return detected_box

    alpha = TRACK_FILTER_ALPHA
    return (
        previous_box[0] + alpha * (detected_box[0] - previous_box[0]),
        previous_box[1] + alpha * (detected_box[1] - previous_box[1]),
        previous_box[2] + alpha * (detected_box[2] - previous_box[2]),
        previous_box[3] + alpha * (detected_box[3] - previous_box[3]),
    )


def normalized_x_to_position_x10(u):
    """Three-point, piecewise-linear calibrated coordinate conversion."""
    u = float(u)
    if u <= CAL_U_ZERO:
        denominator = CAL_U_ZERO - CAL_U_NEG120
        if denominator <= 0:
            return 0
        ratio = (u - CAL_U_NEG120) / denominator
        position_x10 = POSITION_MIN_X10 + clamp(ratio, 0.0, 1.0) * 1200.0
    else:
        denominator = CAL_U_POS120 - CAL_U_ZERO
        if denominator <= 0:
            return 0
        ratio = (u - CAL_U_ZERO) / denominator
        position_x10 = clamp(ratio, 0.0, 1.0) * 1200.0
    return int(round(clamp(
        position_x10, POSITION_MIN_X10, POSITION_MAX_X10
    )))


def position_x10_to_normalized_x(position_x10):
    """Inverse of the three-point calibrated position conversion."""
    position_x10 = clamp(
        int(position_x10), POSITION_MIN_X10, POSITION_MAX_X10
    )
    if position_x10 <= 0:
        ratio = float(position_x10 - POSITION_MIN_X10) / 1200.0
        return CAL_U_NEG120 + ratio * (CAL_U_ZERO - CAL_U_NEG120)
    ratio = float(position_x10) / 1200.0
    return CAL_U_ZERO + ratio * (CAL_U_POS120 - CAL_U_ZERO)


def track_x_to_position_x10(x, track_box):
    """Map an LCD X coordinate on the track to calibrated physical position."""
    if track_box is None or track_box[2] <= 0:
        return 0
    u = (float(x) - float(track_box[0])) / float(track_box[2])
    return normalized_x_to_position_x10(u)


def position_x10_to_track_x(position_x10, track_box):
    """Convert a physical setpoint back to an LCD X coordinate."""
    if track_box is None:
        return 0
    u = position_x10_to_normalized_x(position_x10)
    return int(round(track_box[0] + u * track_box[2]))


def touch_is_on_track(touch_x, touch_y, track_box):
    """Accept a touch inside the calibrated track X range and near its Y."""
    if track_box is None:
        return False

    left = track_box[0] + CAL_U_NEG120 * track_box[2]
    right = track_box[0] + CAL_U_POS120 * track_box[2]
    top = track_box[1] - TOUCH_Y_MARGIN_PX
    bottom = track_box[1] + track_box[3] + TOUCH_Y_MARGIN_PX
    return left <= touch_x <= right and top <= touch_y <= bottom


def touch_x_to_mode(touch_x, touch_y, screen_width):
    """Return selected mode for a new button press, or 0 when not a button."""
    if touch_y < 0 or touch_y >= UI_BUTTON_HEIGHT_PX:
        return 0
    button_width = float(screen_width) / 3.0
    mode = int(float(touch_x) / button_width) + 1
    return int(clamp(mode, MODE_CENTER, MODE_TOUCH))


def draw_target_marker(osd_img, setpoint_x10, setpoint_valid, track_box):
    """Draw the active setpoint on the detected track."""
    if not setpoint_valid or track_box is None:
        return

    marker_x = position_x10_to_track_x(setpoint_x10, track_box)
    marker_y = int(round(track_box[1] + track_box[3] * 0.5))
    marker_x = int(clamp(marker_x, 0, display_size[0] - 1))
    marker_y = int(clamp(marker_y, 0, display_size[1] - 1))

    osd_img.draw_circle(
        marker_x, marker_y, 12,
        color=(255, 0, 255, 0),
        thickness=3,
    )
    osd_img.draw_cross(
        marker_x, marker_y,
        color=(255, 0, 255, 0),
        size=16,
        thickness=3,
    )

    text_x = int(clamp(marker_x - 70, 0, display_size[0] - 170))
    text_y = int(clamp(
        marker_y - 50, UI_BUTTON_HEIGHT_PX + 2, display_size[1] - 28
    ))
    osd_img.draw_string_advanced(
        text_x,
        text_y,
        24,
        "SET:{:.1f}mm".format(setpoint_x10 / 10.0),
        color=(255, 0, 255, 0),
    )


def draw_mode_ui(
    osd_img,
    current_mode,
    setpoint_valid,
    mode2_phase,
    mode2_elapsed_ms,
    mode2_done,
):
    """Draw three touch buttons and mode status."""
    button_width = display_size[0] // 3
    labels_text = ("M1 CENTER", "M2 +50/-50", "M3 TOUCH")

    for index in range(3):
        mode = index + 1
        x = index * button_width
        width = (
            display_size[0] - x
            if index == 2
            else button_width
        )
        color = (
            (255, 0, 255, 0)
            if mode == current_mode
            else (255, 255, 255, 255)
        )
        osd_img.draw_rectangle(
            x, 0, width, UI_BUTTON_HEIGHT_PX,
            color=color,
            thickness=3,
        )
        osd_img.draw_string_advanced(
            x + 8, 17, 20, labels_text[index], color=color
        )

    if current_mode == MODE_CENTER:
        status = "MODE1: HOLD 0.0mm"
        status_color = (255, 0, 255, 0)
    elif current_mode == MODE_SWEEP:
        if mode2_phase == MODE2_GO_POSITIVE:
            phase_text = "GO +50mm"
        elif mode2_phase == MODE2_GO_NEGATIVE:
            phase_text = "GO -50mm"
        else:
            phase_text = "HOLD -50mm"
        status = "MODE2: {}  {:.2f}s".format(
            phase_text, mode2_elapsed_ms / 1000.0
        )
        if mode2_done:
            status_color = (255, 0, 255, 0)
        elif mode2_elapsed_ms > MODE2_TIME_LIMIT_MS:
            status_color = (255, 255, 0, 0)
        else:
            status_color = (255, 255, 255, 0)
    elif setpoint_valid:
        status = "MODE3: TOUCH TARGET ACTIVE"
        status_color = (255, 0, 255, 0)
    else:
        status = "MODE3: TOUCH THE TRACK"
        status_color = (255, 255, 255, 0)

    osd_img.draw_string_advanced(
        10,
        UI_BUTTON_HEIGHT_PX + 5,
        22,
        status,
        color=status_color,
    )


def draw_ball_status(
    osd_img,
    ball_fresh,
    ball_valid,
    edge_recovery_side,
):
    """Show whether UART position is measured, predicted or in recovery."""
    if ball_fresh:
        status = "BALL: DETECTED"
        status_color = (255, 0, 255, 0)
    elif edge_recovery_side < 0:
        status = "BALL: LEFT EDGE RECOVERY"
        status_color = (255, 255, 0, 0)
    elif edge_recovery_side > 0:
        status = "BALL: RIGHT EDGE RECOVERY"
        status_color = (255, 255, 0, 0)
    elif ball_valid:
        status = "BALL: SHORT PREDICTION"
        status_color = (255, 255, 255, 0)
    else:
        status = "BALL: LOST / POSITION INVALID"
        status_color = (255, 255, 0, 0)

    osd_img.draw_string_advanced(
        10,
        UI_BUTTON_HEIGHT_PX + 33,
        20,
        status,
        color=status_color,
    )


pl = None
yolo = None
uart4 = None
touch = None

try:
    # GPIO36/37 pin multiplexing for K230 UART4.
    fpioa = FPIOA()
    fpioa.set_function(36, FPIOA.UART4_TXD)
    fpioa.set_function(37, FPIOA.UART4_RXD)

    uart4 = UART(
        UART.UART4,
        baudrate=115200,
        bits=UART.EIGHTBITS,
        parity=UART.PARITY_NONE,
        stop=UART.STOPBITS_ONE,
    )

    pl = PipeLine(
        rgb888p_size=rgb888p_size,
        display_size=display_size,
        display_mode=display_mode,
    )

    if display == "lcd2_4":
        pl.create(sensor=Sensor(id=2, width=1280, height=960))
    else:
        pl.create(sensor=Sensor(id=2, width=1920, height=1080))

    display_size = pl.get_display_size()

    # System default touch coordinates normally follow the LCD orientation.
    if display != "hdmi":
        touch = TOUCH(0)

    yolo = YOLO11(
        task_type="detect",
        mode="video",
        kmodel_path=kmodel_path,
        labels=labels,
        rgb888p_size=rgb888p_size,
        model_input_size=model_input_size,
        display_size=display_size,
        conf_thresh=confidence_threshold,
        nms_thresh=nms_threshold,
        max_boxes_num=50,
        debug_mode=0,
    )
    yolo.config_preprocess()

    clock = time.clock()
    sequence = 0

    filtered_track_box = None
    last_track_time_ms = time.ticks_ms()

    current_mode = DEFAULT_MODE
    mode3_setpoint_valid = False
    mode3_setpoint_x10 = 0
    touch_was_active = False

    mode2_phase = MODE2_GO_POSITIVE
    mode2_start_ms = time.ticks_ms()
    mode2_in_range_since_ms = -1
    mode2_done = False

    previous_ball_valid = False
    filtered_ball_position_x10 = None
    filtered_ball_velocity_x10 = None
    last_ball_detection_time_ms = time.ticks_ms()
    last_fresh_position_x10 = 0
    last_fresh_velocity_x10 = 0
    last_ball_confidence_percent = 0
    last_ball_center_x = None

    while True:
        clock.tick()

        img = pl.get_frame()
        detections = yolo.run(img)
        yolo.draw_result(detections, pl.osd_img)
        now_ms = time.ticks_ms()

        # Detect and smooth the beam coordinate frame.
        track_detection = select_class(detections, TRACK_CLASS_ID)
        track_fresh = track_detection is not None
        if track_fresh:
            detected_track_box, _ = track_detection
            filtered_track_box = filter_track_box(
                filtered_track_box, detected_track_box
            )
            last_track_time_ms = now_ms
        elif (
            filtered_track_box is not None
            and time.ticks_diff(now_ms, last_track_time_ms) > TRACK_HOLD_MS
        ):
            filtered_track_box = None

        # Read LCD touch. Buttons react once per press; mode-3 target supports
        # continuous dragging along the track.
        touch_active = False
        if touch is not None:
            touch_points = touch.read(1)
            if touch_points is not None and len(touch_points) > 0:
                point = touch_points[0]
                if int(point.event) != TOUCH.EVENT_UP:
                    touch_active = True
                    touch_x = int(point.x)
                    touch_y = int(point.y)

                    if not touch_was_active:
                        selected_mode = touch_x_to_mode(
                            touch_x, touch_y, display_size[0]
                        )
                        if selected_mode != 0:
                            current_mode = selected_mode
                            if current_mode == MODE_SWEEP:
                                mode2_phase = MODE2_GO_POSITIVE
                                mode2_start_ms = now_ms
                                mode2_in_range_since_ms = -1
                                mode2_done = False

                    if (
                        current_mode == MODE_TOUCH
                        and touch_y >= UI_BUTTON_HEIGHT_PX
                        and touch_is_on_track(
                            touch_x, touch_y, filtered_track_box
                        )
                    ):
                        mode3_setpoint_x10 = track_x_to_position_x10(
                            touch_x, filtered_track_box
                        )
                        mode3_setpoint_valid = True

        touch_was_active = touch_active

        # Convert the detected ball center into the beam-relative coordinate.
        ball_detection = select_class(
            detections,
            BALL_CLASS_ID,
            last_ball_center_x if previous_ball_valid else None,
            BALL_ASSOCIATION_MAX_JUMP_PX,
        )
        ball_fresh = (
            ball_detection is not None
            and filtered_track_box is not None
        )
        edge_recovery = False
        edge_recovery_side = 0

        if ball_fresh:
            ball_box, ball_confidence = ball_detection
            ball_center_x = ball_box[0] + ball_box[2] * 0.5
            confidence_percent = int(round(
                clamp(ball_confidence, 0.0, 1.0) * 100.0
            ))
            raw_position_x10 = track_x_to_position_x10(
                ball_center_x, filtered_track_box
            )
            if filtered_ball_position_x10 is None:
                position_x10 = raw_position_x10
            else:
                position_x10 = int(round(
                    filtered_ball_position_x10
                    + BALL_POSITION_FILTER_ALPHA
                    * (raw_position_x10 - filtered_ball_position_x10)
                ))
            filtered_ball_position_x10 = position_x10

            # Velocity is calculated between real detections, not between a
            # prediction and a detection. This makes the outward-direction
            # decision less sensitive to one missed frame.
            if last_ball_center_x is not None:
                dt_ms = time.ticks_diff(
                    now_ms, last_ball_detection_time_ms
                )
                if dt_ms > 0:
                    raw_velocity_x10 = int(round(
                        (position_x10 - last_fresh_position_x10)
                        * 1000.0 / dt_ms
                    ))
                    raw_velocity_x10 = clamp(
                        raw_velocity_x10, -32768, 32767
                    )
                    if filtered_ball_velocity_x10 is None:
                        velocity_x10 = raw_velocity_x10
                    else:
                        velocity_x10 = int(round(
                            filtered_ball_velocity_x10
                            + BALL_VELOCITY_FILTER_ALPHA
                            * (
                                raw_velocity_x10
                                - filtered_ball_velocity_x10
                            )
                        ))
                else:
                    velocity_x10 = 0
            else:
                velocity_x10 = 0
            filtered_ball_velocity_x10 = velocity_x10

            previous_ball_valid = True
            last_ball_detection_time_ms = now_ms
            last_fresh_position_x10 = position_x10
            last_fresh_velocity_x10 = velocity_x10
            last_ball_confidence_percent = confidence_percent
            last_ball_center_x = ball_center_x
            ball_valid = True

        elif previous_ball_valid and filtered_track_box is not None:
            hold_age_ms = time.ticks_diff(
                now_ms, last_ball_detection_time_ms
            )
            (
                ball_valid,
                position_x10,
                velocity_x10,
                confidence_percent,
                edge_recovery_side,
            ) = predict_missing_ball_state(
                last_fresh_position_x10,
                last_fresh_velocity_x10,
                last_ball_confidence_percent,
                hold_age_ms,
            )
            edge_recovery = edge_recovery_side != 0

            # Do not feed a blind prediction back into the measurement
            # filter. A fresh detection can then take over smoothly from the
            # last real observation instead of from an assumed end.
            if not ball_valid:
                confidence_percent = 0
                position_x10 = 0
                velocity_x10 = 0
                previous_ball_valid = False
                filtered_ball_position_x10 = None
                filtered_ball_velocity_x10 = None
                last_ball_center_x = None
                ball_valid = False

        else:
            confidence_percent = 0
            position_x10 = 0
            velocity_x10 = 0
            previous_ball_valid = False
            filtered_ball_position_x10 = None
            filtered_ball_velocity_x10 = None
            last_ball_center_x = None
            ball_valid = False

        # Generate the active setpoint and mode-2 state sequence.
        if current_mode == MODE_CENTER:
            active_setpoint_valid = True
            active_setpoint_x10 = 0
            mode2_elapsed_ms = 0

        elif current_mode == MODE_SWEEP:
            mode2_elapsed_ms = time.ticks_diff(now_ms, mode2_start_ms)

            if mode2_phase == MODE2_GO_POSITIVE:
                active_setpoint_x10 = MODE2_POSITIVE_X10
                if (
                    ball_fresh
                    and abs(position_x10 - MODE2_POSITIVE_X10)
                    <= MODE2_TOLERANCE_X10
                ):
                    mode2_phase = MODE2_GO_NEGATIVE
                    mode2_in_range_since_ms = -1
                    active_setpoint_x10 = MODE2_NEGATIVE_X10

            elif mode2_phase == MODE2_GO_NEGATIVE:
                active_setpoint_x10 = MODE2_NEGATIVE_X10
                if (
                    ball_fresh
                    and abs(position_x10 - MODE2_NEGATIVE_X10)
                    <= MODE2_TOLERANCE_X10
                ):
                    if mode2_in_range_since_ms < 0:
                        mode2_in_range_since_ms = now_ms
                    elif (
                        time.ticks_diff(
                            now_ms, mode2_in_range_since_ms
                        )
                        >= MODE2_SETTLE_MS
                    ):
                        mode2_phase = MODE2_HOLD_NEGATIVE
                        mode2_done = True
                else:
                    mode2_in_range_since_ms = -1

            else:
                active_setpoint_x10 = MODE2_NEGATIVE_X10

            active_setpoint_valid = True

        else:
            active_setpoint_valid = mode3_setpoint_valid
            active_setpoint_x10 = mode3_setpoint_x10
            mode2_elapsed_ms = 0

        flags = (current_mode & 0x03) << MODE_FLAG_SHIFT
        if ball_valid:
            flags |= FLAG_BALL_VALID
        if active_setpoint_valid:
            flags |= FLAG_SETPOINT_VALID
        if track_fresh:
            flags |= FLAG_TRACK_FRESH
        if current_mode == MODE_SWEEP and mode2_done:
            flags |= FLAG_MODE2_DONE
        if ball_fresh:
            flags |= FLAG_BALL_FRESH
        if edge_recovery:
            flags |= FLAG_EDGE_RECOVERY

        packet = build_packet(
            sequence,
            flags,
            confidence_percent,
            position_x10,
            velocity_x10,
            active_setpoint_x10,
        )
        uart4.write(packet)

        # YOLO draw_result clears the OSD, so draw UI afterward.
        draw_target_marker(
            pl.osd_img,
            active_setpoint_x10,
            active_setpoint_valid,
            filtered_track_box,
        )
        draw_mode_ui(
            pl.osd_img,
            current_mode,
            active_setpoint_valid,
            mode2_phase,
            mode2_elapsed_ms,
            mode2_done,
        )
        draw_ball_status(
            pl.osd_img,
            ball_fresh,
            ball_valid,
            edge_recovery_side,
        )

        if DEBUG_PRINT:
            print(
                "seq:", sequence,
                "mode:", current_mode,
                "flags:", flags,
                "ball_x10:", position_x10,
                "vel_x10:", velocity_x10,
                "set_x10:", active_setpoint_x10,
                "edge:", edge_recovery_side,
                "phase:", mode2_phase,
                "fps:", clock.fps(),
            )

        sequence = (sequence + 1) & 0xFF
        pl.show_image()
        gc.collect()

except Exception as e:
    sys.print_exception(e)

finally:
    if yolo is not None:
        yolo.deinit()
    if touch is not None:
        touch.deinit()
    if pl is not None:
        pl.destroy()
    if uart4 is not None:
        uart4.deinit()
    gc.collect()
